version: '3.3'
volumes:
  pg_data:
  static:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: imuntouchable/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  frontend:
    container_name: foodgram-front
    image: imuntouchable/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
      - ../frontend/:/app/result_build/
  nginx:
    image: imuntouchable/foodgram_nginx
    volumes:
      - static:/staticfiles/
    ports:
      - 80:80
